#! /usr/bin/python

import os
import os.path
import sys

if len(sys.argv)<2:
	print("Usage: setresume sd[letter][number]")
	print("This script will set the kernel's resume devive you have to run")
	print("grub-mkconfig -o /boot/grub/grub.cfg")
	print("after running this script.")
	exit()

text=os.popen("""grep -m 1 -o "resume=[[:alnum:][:punct:]]*" /etc/default/grub""").read()[:-1]
grubcfg=open("/etc/default/grub","r").read()

device=sys.argv[1]
repl=""
for d in os.popen("ls /dev/disk/by-uuid"):
	if os.path.realpath("/dev/disk/by-uuid/"+d[:-1]) == "/dev/"+ device:
		repl=d[:-1]

if repl!="":
	print(grubcfg.replace(text,"resume=UUID="+repl))
else:
	print("# Resume device not found!, dumping old cfg in case you made it redirect to file")
	print(grubcfg)
